# Generated by Django 4.2.7 on 2023-11-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='passwordrepeat',
        ),
    ]
