# Generated by Django 4.2.7 on 2023-11-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/images/logo.png', upload_to='uploads/images'),
        ),
    ]
