# Generated by Django 4.2.7 on 2023-11-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
