# Generated by Django 4.2.7 on 2023-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
